apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: mattermost
  labels:
    app: mattermost
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    name: http
    nodePort: 30001
  selector:
    app: mattermost
