apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace:
    mattermost
data:
  POSTGRES_DB: mattermost
  POSTGRES_USER: mmuser
  POSTGRES_PASSWORD: mmuser_password
