apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-postgres-pvc
  namespace: mattermost
  labels:
    app: postgres
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: mattermost-postgres-pv
